export const SHORT_CODE = {
  SETTINGS: "SETTINGS",
  UIN_CONFIG: "UIN_CONFIG",
  HOSPITAL: "HOSPITAL",
  COLLECTION_CENTER: "COLLECTION_CENTER",
  BLOOD_BANK_CENTER: "BLOOD_BANK_CENTER",
  BLOOD_COMPONENT: "BLOOD_COMPONENT",
  BLOOD_CROSS_MATCH_METHOD: "BLOOD_CROSS_MATCH_METHOD",
  BLOOD_PHYSICAL_EXAM_QUESTION: "BLOOD_PHYSICAL_EXAM_QUESTION",
  BLOOD_EXTERNAL_CENTER: "BLOOD_EXTERNAL_CENTER",
};
