export const SHORT_CODE = {
  COUNTRY: "COUNTRY",
  CITY: "CITY",
  STATE: "STATE",
  EMAIL_CONFIG: "EMAIL_CONFIG",
  SETTINGS: "SETTINGS",
  UIN_CONFIG: "UIN_CONFIG",
  ITEM_CATEGORY: "ITEM_CATEGORY",
  COUNTRY_CODE: "COUNTRY_CODE",
  COLLECTION_CENTER: "COLLECTION_CENTER",
  DOCTOR: "DOCTOR",
  EMPLOYEE: "EMPLOYEE",
  STAFF: "STAFF",
  DEPARTMENT: "DEPARTMENT",
  DESIGNATION: "DESIGNATION",
  CURRENCY: "CURRENCY",
  SERVICE_EVENT: "SERVICE_EVENT",
  TEMPLATE: "TEMPLATE",
  EVENT_CONFIG: "EVENT_CONFIG",
  CORE_APPROVAL: "CORE_APPROVAL",
  PDF_TEMPLATE: "PDF_TEMPLATE",
};

export const CORE_SHORT_CODE_TO_FILE_ATTR = {
  [SHORT_CODE.EMPLOYEE]: "image",
};
