export enum PermissionType {
  CREATE = "add",
  VIEW = "view",
  UPDATE = "edit",
  DELETE = "delete",
  APPROVE = "approve",
  REJECT = "reject",
}

export enum PermissionResource {
  // INVENTORY
  EXPENSE_HEAD = "expense-head",
  EXPENSE = "expense",
  INCOME_HEAD = "income-head",
  INCOME = "income",
  STORAGE = "storage",
  TAX_DETAILS = "tax-details",
  DYNAMIC_FROM = "dynamic-from",
  SETTING = "settings",
  ITEM_SUPPLIER = "item-supplier",
  ITEM_CATEGORY = "item-category",
  ITEM_STORE = "item-store",
  UNIT_MASTER = "unit-master",
  UIN_CONFIG = "uin-config",
  ITEM_MASTER = "item-master",
  ITEM_SUPPLIER_MAP = "item-supplier-map",
  BRANCH = "branch",
  WAREHOUSE = "warehouse",
  CACHE = "cache",
  PURCHASE_ORDER = "purchase-order",
  ITEM_SEARCH = "item-search",
  GRN = "grn",
  GRN_PDF = "grn-pdf",
  GRN_RETURN = "grn-return",
  GRN_RETURN_APPROVE = "grn-return-approve",
  GRN_RETURN_REJECTED = "grn-return-rejected",
  GRN_RETURN_PDF = "grn-return-pdf",
  STORE_REQUISITION = "store-requisition",
  STORE_REQUISITION_REJECT = "storeRequisition-reject",
  STORE_REQUISITION_SENT = "storeRequisition-sent",
  STORE_REQUISITION_ACK = "storeRequisition-acknowledge",
  LOCATION = "location",
  CONSUMPTION = "consumption",
  ITEM_BATCHES = "item-batch",
  ITEMS_SUP = "items-supplier",
  ITEM_STOCK = "item-stock",
  ITEM_STOCK_SUMMARY = "item-stock-summary",
  CURRENCY = "currency",
  STOCK_ADJUSTMENT = "stock-adjustment",
  COLLECTION_CENTER = "collection-center",

  // CORE
  COUNTRY = "country",
  STATE = "state",
  CITY = "city",
  PDF_TEMPLATE = "pdf-template",
  PDF_CONTRACT = "pdf-contract",
  COUNTRY_CODE = "countryCode",
  STAFF = "staff",
  STAFF_DESIGNATION = "staffDesignation",
  STAFF_EMPLOYEE = "staffEmployee",
  DEPARTMENT = "department",
  DOCTOR = "doctor",
  EMPLOYEE = "employee",
  STAFF_COLLECTION_CENTER = "staffCollectionCenter",
  SERVICE_EVENT = "service-event",
  TEMPLATE = "template",
  EVENT_CONFIG = "event-config",
  NOTIFICATION = "notification",
  EVENT_RECIPIENT_RULE = "event-recipient-rule",
  CORE_APPROVAL = "core-approval",

  // OPD
  PATIENT = "patients",
  OPD_DEPARTMENT = "opd-department",
  OPD_DEPARTMENT_PREFIX = "opd-department-prefix",
  CLINICAL_HISTORY = "clinical-history",
  REFER_TO_DOCTOR = "refer-to-doctor",
  PATIENT_CONSULTATION = "patient-consultation",
  CONSULTATION_COMPLAINTS = "consultation-complaints",
  PATIENT_ADVICE_DETAILS = "patient-advice-details",
  TIME_SLOT = "time-slot",
  DOCUMENT = "document",
  APPOINTMENT = "appointment",
  PATIENT_MEDICINE = "patient-medicine",
  FOLLOW_UP = "follow-up",
  CHIPS_BUTTON_MAPPING = "chips-button-mapping",
  CONSULTATION_ICD_TEN_LIST = "consultation-icd-ten-list",
  ICD_TEN = "icd-ten",
  CONSULTATION_NOTES = "consultation-notes",
  CONSULTATION_NOTES_MAPPING = "consultation-notes-mapping",
  PATIENT_INSURANCE = "patient-insurance",
  INSURANCE = "insurance",
  CONSULTATION = "consultation",
  PATHOLOGY_MASTER = "pathology-master",
  TEST_CATEGORIES = "test-categories",
  TESTS = "tests",
  PATIENT_TEST = "patient-test",
  MEDICINE_TAB = "medicine-tab",
  MEDICINE_TAB_DETAILS = "medicine-tab-details",
  PROCEDURE = "procedure",
  PATIENT_PROCEDURE = "patient-procedure",
  DOCTOR_FEES = "doctor-fees",
  PAYMENT = "payment",
  BANK_HEAD = "cash-n-bank-head",
  MOBILE_MONEY = "mobile-money-method",
  GENERAL_BILLING = "general-billing",
  GENERAL_BILL_ITEM = "general-bill-item",
  GENERAL_BILL_PRICING = "general-bill-pricing",
}

export enum PermissionModule {
  PMS = "pms",
  OPD = "opd",
  CORE = "core",
  INV = "inv",
}

export const getPermission = (
  module: keyof typeof PermissionModule,
  resource: keyof typeof PermissionResource,
  type: keyof typeof PermissionType,
): string => {
  return `${module}:${PermissionResource[resource]}:${PermissionType[type]}`;
};
